# Generated by Django 6.0.2 on 2026-02-22 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique identifier for this chat session', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('free_text_symptoms', models.TextField(blank=True, help_text="Raw symptoms user described that we couldn't match")),
                ('current_urgency', models.CharField(blank=True, choices=[('emergency', 'Emergency - seek immediate medical attention'), ('urgent', 'Urgent - see a doctor within 24 hours'), ('morderate', 'Moderate - Monitor or Schedule appoinment'), ('self_care', 'Self-care - Home treatment sufficient]')], max_length=20, null=True)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the symptom.')),
                ('body_system', models.CharField(choices=[('general', 'General'), ('respiratory', 'Respiratory'), ('cardiovascular', 'Cardiovascular'), ('neurological', 'Neurological'), ('musculoskeletal', 'Musculoskeletal')], default='general', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('extracted_symptoms', models.JSONField(blank=True, default=list, help_text='Symptoms extracted from this message')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='reported_symptoms',
            field=models.ManyToManyField(blank=True, related_name='chat_sessions', to='chatbot.symptom'),
        ),
        migrations.CreateModel(
            name='UrgencyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nanme of this rule', max_length=100)),
                ('urgency_level', models.CharField(choices=[('emergency', 'Emergency - seek immediate medical attention'), ('urgent', 'Urgent - see a doctor within 24 hours'), ('morderate', 'Moderate - Monitor or Schedule appoinment'), ('self_care', 'Self-care - Home treatment sufficient]')], max_length=20)),
                ('requires_all', models.BooleanField(default=True, help_text='If True, ALL listed symptoms must be present. If False, ANY one symptom triggers this.')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are checked first')),
                ('guidance_text', models.TextField(help_text='What to tell the user when this rule matches')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symptoms', models.ManyToManyField(related_name='urgency_rules', to='chatbot.symptom')),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
    ]
