# Generated by Django 6.0.2 on 2026-03-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='duration_known',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='severity_known',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='stage',
            field=models.CharField(choices=[('gathering', 'Gathering information'), ('assessing', 'Assessing symptoms'), ('complete', 'Assessment complete')], default='gathering', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='current_urgency',
            field=models.CharField(blank=True, choices=[('emergency', 'Emergency - seek immediate medical attention'), ('urgent', 'Urgent - see a doctor within 24 hours'), ('moderate', 'Moderate - Monitor or Schedule appoinment'), ('self_care', 'Self-care - Home treatment sufficient]')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='urgencyrule',
            name='name',
            field=models.CharField(help_text='Name of this rule', max_length=100),
        ),
        migrations.AlterField(
            model_name='urgencyrule',
            name='urgency_level',
            field=models.CharField(choices=[('emergency', 'Emergency - seek immediate medical attention'), ('urgent', 'Urgent - see a doctor within 24 hours'), ('moderate', 'Moderate - Monitor or Schedule appoinment'), ('self_care', 'Self-care - Home treatment sufficient]')], max_length=20),
        ),
    ]
