# Generated by Django 6.0.2 on 2026-03-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatsession_duration_known_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='additional_symptoms_asked',
            field=models.BooleanField(default=False),
        ),
    ]
