# Generated by Django 6.0.2 on 2026-03-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatsession_additional_symptoms_asked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('urgency_level', models.CharField(choices=[('emergency', 'Emergency - seek immediate medical attention'), ('urgent', 'Urgent - see a doctor within 24 hours'), ('moderate', 'Moderate - Monitor or Schedule appoinment'), ('self_care', 'Self-care - Home treatment sufficient]')], default='moderate', max_length=20)),
                ('precautions', models.TextField(blank=True, help_text='Comma-separated list of precautions')),
                ('symptoms', models.ManyToManyField(blank=True, related_name='diseases', to='chatbot.symptom')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
