# Generated by Django 6.0.2 on 2026-05-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='current_interview_phase',
            field=models.CharField(choices=[('intro', 'Initial contact - understanding main complaint'), ('core_characterization', 'Questions 1-3: Onset, duration, quality, severity, location'), ('associated_symptoms', 'Questions 4-6: Associated symptoms & modifying factors'), ('history_meds', 'Questions 7-8: Past history & medications'), ('complete', 'Assessment complete')], default='intro', max_length=50),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='questions_asked_in_phase',
            field=models.IntegerField(default=0, help_text='Count of follow-up questions asked in current phase'),
        ),
    ]
